---
- name: Install prerequisite into reddit-db-base disk image
  hosts: all
  become: true
  tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
        state: present

    - name: Add repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Update apt cache
      apt:
       update_cache: yes

    - name: Install packages mongodb-org
      apt: name={{item}} state=present
      with_items:
       - mongodb-org

    - name: enable mongodb service
      systemd:
        name: mongod
        state: started
        enabled: True
