---
- name: Install prerequisite into reddit-app-base disk image
  hosts: all
  become: true
  tasks:
    - name: Install packages ruby-full ruby-bundler build-essential
      apt: name={{item}} state=present
      with_items:
       - ruby-full
       - ruby-bundler
       - build-essential
